language: java
dist: trusty
sudo: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.m2
jdk:
- oraclejdk8
- openjdk8
script: ./gradlew jacocoTestReport ;
after_success:
- echo "TRAVIS_BRANCH='$TRAVIS_BRANCH'"; echo "JAVA_HOME='$JAVA_HOME'";
- bash <(curl -s https://raw.githubusercontent.com/broadinstitute/codecov-bash-uploader/main/codecov-verified.bash); if [ "$TRAVIS_BRANCH" == "master" ]; then
  ./gradlew uploadArchives; fi
