package org.broadinstitute.barclay.argparser;

import java.lang.annotation.*;

/**
 * Used to annotate which fields of a CommandLineProgram are input or output file resources from the perspective
 * of a workflow execution engine.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Documented
public @interface WorkflowResource {
    /**
     * @return true if the argument is an input resource
     */
    boolean input() default false;

    /**
     * @return true if the argument is an output resource
     */
    boolean output() default true;

    /**
     * @return array of names of companion files that should travel with this resource. For example, a (Genomic
     * Reference) FASTA file might have two associated companion files that must be supplied as arguments to the
     * workflow, so the WorkflowResource would use the attribute values:
     *
     * @WorkflowResource(companionResources = {"referenceDictionary", "referenceIndex" }
     *
     * The associated workflow and workflow input JSON (but not the task) generated by Barclay will contain two
     * additional optional parameters with these names, allowing callers to optionally provide name values for
     * the companion files.
     *
     * The additional arguments will be included in the workflow output section of the associated WDL for
     * resources that have output=true.
     */
    String[] companionResources() default {};
}
